
#### This stub was autogenerated by Typedpy
###########################################

from typing import Union, Optional, Any
from typedpy import Structure
import enum

class JobController:

    
    def __init__(self, urls: dict[str, dict]): ...
    
    def execute(self, job_id: str): ...

