
#### This stub was autogenerated by Typedpy
###########################################

from typing import Union, Optional, Any, TypeVar, Type, NoReturn
from typedpy import Structure

from datetime import datetime as datetime
from examples.subpackage.apis import Vehicle as Vehicle
from typedpy import create_pyi as create_pyi
from examples.controllers.job_controller import JobController as JobController


class ScheduledController(JobController):

    d:  datetime

    def __init__(self, *args, d: datetime, job_controller: JobController, vehicle: Vehicle, **kw): ...

    def is_it_time(self, *, a = None) -> bool: ...

