
#### This stub was autogenerated by Typedpy
###########################################

from typing import Union, Optional, Any, TypeVar
from typedpy import Structure
import enum



from datetime import datetime
from examples.more_classes import Person
from examples import Foo
from .apis import Vehicle

class FooOmitSubPackage(Structure):
    def __init__(
        self,
        i: int,
        s: str,
        person: Person,
        dob: datetime,
        arr: list[str],
        union: Union[int,str],
        any: Any,
        x: int,
        d: Optional[dict[str, int]] = None,
        **kw
    ): ...

    i: int
    s: str
    person: Person
    dob: datetime
    arr: list[str]
    union: Union[int,str]
    any: Any
    x: int
    d: Optional[dict[str, int]] = None

