
#### This stub was autogenerated by Typedpy
###########################################

from typing import Union, Optional, Any
from typedpy import Structure
import enum

from examples.enums import State

class Vehicle(Structure):
    def __init__(,
        self,
        license_plate_state: State,
        odometer: int,
        alias: str,
        license_plate: str,
        **kw
    ): ...

    license_plate_state: State
    odometer: int
    alias: str
    license_plate: str

