
#### This stub was autogenerated by Typedpy
###########################################

from typing import Union, Optional, Any
from typedpy import Structure
import enum

from datetime import datetime
from examples.more_classes import Person
from examples.api_example import Foo
from examples.enums import State

class Vehicle(Structure):
    def __init__(
        self,
        license_plate_state: State,
        odometer: int,
        alias: str,
        license_plate: str,
        **kw
    ): ...

    license_plate_state: State
    odometer: int
    alias: str
    license_plate: str


class AnotherFoo(Structure):
    def __init__(
        self,
        i: int,
        s: str,
        person: Person,
        dob: datetime,
        arr: list[str],
        union: Union[int,str],
        any: Any,
        a: set,
        b: set,
        another: str,
        d: Optional[dict[str, int]] = None,
        **kw
    ): ...

    i: int
    s: str
    person: Person
    dob: datetime
    arr: list[str]
    union: Union[int,str]
    any: Any
    a: set
    b: set
    another: str
    d: Optional[dict[str, int]] = None


class Vehicle2(Structure):
    def __init__(
        self,
        license_plate_state: Optional[State] = None,
        odometer: Optional[int] = None,
        alias: Optional[str] = None,
        license_plate: Optional[str] = None,
        **kw
    ): ...

    license_plate_state: Optional[State] = None
    odometer: Optional[int] = None
    alias: Optional[str] = None
    license_plate: Optional[str] = None

