
#### This stub was autogenerated by Typedpy
###########################################

from typing import Union, Optional, Any, TypeVar, Type
from typedpy import Structure
import enum



class State(enum.Enum):
    NY = enum.auto()
    NJ = enum.auto()
    AL = enum.auto()
    FL = enum.auto()


    
    @staticmethod
    def by_foo(): ...
    
    @classmethod
    def cls_method(cls, i: int) -> int: ...
    
    @property
    def aaa(self): ...


class Sex(enum.Enum):
    male = enum.auto()
    female = enum.auto()



