
#### This stub was autogenerated by Typedpy
###########################################

from typing import Union, Optional, Any, TypeVar, Type, NoReturn
from typedpy import Structure

from enum import Enum as Enum
from typedpy import create_pyi as create_pyi
import enum



class Status(enum.Enum):
    status1 = enum.auto()
    status2 = enum.auto()
    status3 = enum.auto()



