
#### This stub was autogenerated by Typedpy
###########################################

from __future__ import annotations as annotations
from typing import Union, Optional, Any, TypeVar, Type, NoReturn, Iterable
from typedpy import Structure

from .more_classes import Address as Address


class FA:

    
    def xyz(self, address: Address) -> FA: ...

