
#### This stub was autogenerated by Typedpy
###########################################

from typing import Union, Optional, Any, TypeVar, Type, NoReturn
from typedpy import Structure
import enum

from .more_classes import Address



class FA:

    
    def xyz(self, address: Address) -> FA: ...

