#### This stub was autogenerated by Typedpy
###########################################

from typing import Union, Optional, Any, Type, NoReturn
from typedpy import Structure

from typing import TypeVar as TypeVar
from typing import Generic as Generic

T = TypeVar("T")

class Stack(Generic[T]):

    _t:  T
    i:  int
    items: list[T]

    def __init__(self, i: int, t: T) -> None: ...

    def push(self, item: T) -> None: ...

    def pop(self) -> T: ...

    def empty(self) -> bool: ...


def func(stack: Stack[int]): ...

