#### This stub was autogenerated by Typedpy
###########################################

from typing import Union, Optional, Any, Type, NoReturn
from typedpy import Structure

from typing import TypeVar as TypeVar
from typing import Generic as Generic

T = TypeVar("T")


class Stack(Generic[T]):

    def __init__(self) -> None: ...

    def push(self, item: T) -> None: ...

    def pop(self) -> T: ...

    def empty(self) -> bool: ...


def func(stack: Stack[int]): ...

